version: 1

formatters:
  simple:
    format: '%(asctime)-15s -%(name)s -%(process)d-%(levelname)s-%(message)s'
handlers:

  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: simple
    filename: './logs/app.log'
#    maxBytes: 1024
#    backupCount: 3

loggers:
  sampleLogger:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console, file]